[package]
name = "fastled-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "FastLED WASM compilation CLI"

[features]
default = ["viewer"]
viewer = ["kernal-api/tauri-webview"]

[lib]
name = "fastled_cli"
path = "src/lib.rs"

[[bin]]
name = "fastled"
path = "src/main.rs"

[dependencies]
kernal-api = { workspace = true }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/fastled-{ target }{ archive-suffix }"
bin-dir = "fastled{ binary-ext }"
pkg-fmt = "zip"
