from __future__ import annotations

import hashlib
import os
import shutil
import struct
import sys
import tarfile
from dataclasses import dataclass
from pathlib import Path

import fasteners
import httpx
import pyzstd

MANIFEST_BASE_URL = "https://raw.githubusercontent.com/zackees/clang-tool-chain-bins/main/assets/emscripten"
ARCHIVE_CACHE_DIR = Path.home() / ".fastled" / "toolchains" / "archives"
INSTALL_ROOT = Path.home() / ".fastled" / "toolchains" / "emscripten"


@dataclass(frozen=True)
class EmscriptenArchivePart:
    href: str
    sha256: str


@dataclass(frozen=True)
class EmscriptenArchive:
    version: str
    href: str
    sha256: str
    parts: tuple[EmscriptenArchivePart, ...]


def _platform_arch() -> tuple[str, str]:
    if sys_platform := sys.platform:
        if sys_platform == "win32":
            platform = "win"
        elif sys_platform == "darwin":
            platform = "darwin"
        else:
            platform = "linux"
    else:
        platform = "linux"

    is_64bit = struct.calcsize("P") * 8 == 64
    uname = getattr(os, "uname", None)
    if uname is not None:
        machine = uname().machine.lower()
    else:
        machine = "amd64" if is_64bit else "x86"

    if machine in ("x86_64", "amd64"):
        arch = "x86_64"
    elif machine in ("arm64", "aarch64"):
        arch = "arm64"
    else:
        arch = machine
    return platform, arch


def _manifest_url(platform: str, arch: str) -> str:
    return f"{MANIFEST_BASE_URL}/{platform}/{arch}/manifest.json"


def _parse_manifest(payload: dict[str, object]) -> EmscriptenArchive:
    latest = payload.get("latest")
    if not isinstance(latest, str) or not latest:
        raise ValueError("Manifest missing latest version")

    versions = payload.get("versions")
    if isinstance(versions, dict):
        raw_entry = versions.get(latest)
    else:
        raw_entry = payload.get(latest)

    if not isinstance(raw_entry, dict):
        raise ValueError(f"Manifest missing archive metadata for {latest}")

    href = raw_entry.get("href")
    sha256 = raw_entry.get("sha256")
    parts = raw_entry.get("parts")
    if not isinstance(href, str) or not isinstance(sha256, str):
        raise ValueError(f"Manifest entry for {latest} is invalid")
    if not isinstance(parts, list) or not parts:
        raise ValueError(f"Manifest entry for {latest} has no parts")

    parsed_parts: list[EmscriptenArchivePart] = []
    for index, part in enumerate(parts):
        if not isinstance(part, dict):
            raise ValueError(f"Manifest part {index} for {latest} is invalid")
        part_href = part.get("href")
        part_sha = part.get("sha256")
        if not isinstance(part_href, str) or not isinstance(part_sha, str):
            raise ValueError(f"Manifest part {index} for {latest} is missing fields")
        parsed_parts.append(EmscriptenArchivePart(href=part_href, sha256=part_sha))

    return EmscriptenArchive(
        version=latest,
        href=href,
        sha256=sha256,
        parts=tuple(parsed_parts),
    )


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _download_file(client: httpx.Client, url: str, destination: Path) -> None:
    with client.stream("GET", url, follow_redirects=True) as response:
        response.raise_for_status()
        with open(destination, "wb") as handle:
            for chunk in response.iter_bytes():
                handle.write(chunk)


def _write_emscripten_config(install_dir: Path) -> None:
    node_path = shutil.which("node") or "node"
    config = "\n".join(
        [
            "# Emscripten configuration file",
            "# Auto-generated by fastled",
            "",
            f"LLVM_ROOT = {str(install_dir / 'bin').replace(os.sep, '/')!r}",
            f"BINARYEN_ROOT = {str(install_dir).replace(os.sep, '/')!r}",
            f"NODE_JS = {node_path!r}",
            "",
        ]
    )
    (install_dir / ".emscripten").write_text(config + "\n", encoding="utf-8")


def _write_ctc_metadata(install_dir: Path) -> None:
    bin_dir = install_dir / "bin"
    emscripten_dir = install_dir / "emscripten"
    python_path = Path(sys.executable)
    node_path = shutil.which("node") or "node"
    suffix = ".exe" if sys.platform == "win32" else ""
    emcc_script = emscripten_dir / "emcc.py"
    empp_script = emscripten_dir / "em++.py"
    wasm_ld = bin_dir / f"wasm-ld{suffix}"

    lines = [
        f"emscripten_dir={emscripten_dir}",
        f"config_path={install_dir / '.emscripten'}",
        f"bin_dir={bin_dir}",
        f"node_path={node_path}",
        f"python_path={python_path}",
        f"emcc_script={emcc_script}",
        f"empp_script={empp_script}",
    ]
    (install_dir / ".ctc-emcc-paths").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
    (install_dir / ".ctc-wasmld-cache").write_text(
        f"wasm_ld_path={wasm_ld}\n", encoding="utf-8"
    )


def _extract_archive(archive_path: Path, install_dir: Path) -> None:
    staging_dir = install_dir.parent / f"{install_dir.name}.staging"
    if staging_dir.exists():
        shutil.rmtree(staging_dir, ignore_errors=True)
    staging_dir.mkdir(parents=True, exist_ok=True)

    with open(archive_path, "rb") as handle:
        with pyzstd.ZstdFile(handle, "rb") as zstd_stream:
            with tarfile.open(fileobj=zstd_stream, mode="r|") as tar:
                tar.extractall(staging_dir, filter="data")

    children = [child for child in staging_dir.iterdir()]
    if len(children) == 1 and children[0].is_dir():
        extracted_root = children[0]
        for child in extracted_root.iterdir():
            shutil.move(str(child), staging_dir / child.name)
        shutil.rmtree(extracted_root, ignore_errors=True)

    (staging_dir / "done.txt").write_text("ok\n", encoding="utf-8")

    if install_dir.exists():
        shutil.rmtree(install_dir, ignore_errors=True)
    staging_dir.replace(install_dir)

    # Write configs AFTER rename so paths reference the final install_dir,
    # not the now-deleted staging_dir.
    _write_emscripten_config(install_dir)
    _write_ctc_metadata(install_dir)


def install_emscripten_from_archive(force: bool = False) -> Path:
    platform, arch = _platform_arch()
    install_base = INSTALL_ROOT / platform / arch
    install_base.mkdir(parents=True, exist_ok=True)
    ARCHIVE_CACHE_DIR.mkdir(parents=True, exist_ok=True)

    lock = fasteners.InterProcessLock(str(install_base / ".install.lock"))
    with lock:
        manifest_path = install_base / "manifest.json"
        with httpx.Client(timeout=120) as client:
            response = client.get(_manifest_url(platform, arch), follow_redirects=True)
            response.raise_for_status()
            manifest_path.write_text(response.text, encoding="utf-8")
            archive = _parse_manifest(response.json())

            install_dir = install_base / archive.version
            done_file = install_dir / "done.txt"
            if done_file.exists() and not force:
                return install_dir

            archive_path = (
                ARCHIVE_CACHE_DIR
                / f"emscripten-{platform}-{arch}-{archive.version}.tar.zst"
            )
            if force and archive_path.exists():
                archive_path.unlink()

            if not archive_path.exists():
                part_dir = (
                    ARCHIVE_CACHE_DIR
                    / f"emscripten-{platform}-{arch}-{archive.version}.parts"
                )
                part_dir.mkdir(parents=True, exist_ok=True)
                with open(archive_path, "wb") as merged:
                    for index, part in enumerate(archive.parts):
                        part_path = part_dir / f"part-{index:02d}"
                        if not part_path.exists():
                            _download_file(client, part.href, part_path)
                        part_hash = _sha256_file(part_path)
                        if part_hash != part.sha256:
                            part_path.unlink(missing_ok=True)
                            raise ValueError(
                                f"Checksum mismatch for {part.href}: {part_hash} != {part.sha256}"
                            )
                        with open(part_path, "rb") as handle:
                            shutil.copyfileobj(handle, merged)

            archive_hash = _sha256_file(archive_path)
            if archive_hash != archive.sha256:
                archive_path.unlink(missing_ok=True)
                raise ValueError(
                    f"Archive checksum mismatch for {archive.href}: {archive_hash} != {archive.sha256}"
                )

        _extract_archive(archive_path, install_dir)
        return install_dir
