"""Thin Python API over the native FastLED Rust extension."""

from .__version__ import __version__
from ._native import (
    BuildArtifacts,
    BuildMode,
    BuildRequest,
    BuildResult,
    BuildService,
    CompileResult,
    archive_available,
    build_available,
    collect_examples,
    copy_frontend_to_output,
    find_example_in_repo,
    find_fastled_repo_upwards,
    find_fastled_viewer,
    find_sketch_by_partial_name,
    find_sketch_directories,
    get_examples,
    init_example,
    init_example_from_repo,
    is_in_order_match,
    looks_like_fastled_repo,
    looks_like_sketch_directory,
    prepare_sketch_selection,
    project_available,
    project_init,
    read_fastled_json_ref,
    resolve_prompt_choice,
    string_diff,
    version,
    viewer_available,
    watch_available,
)


class Api:
    get_examples = staticmethod(get_examples)
    project_init = staticmethod(project_init)


__all__ = [
    "Api",
    "BuildArtifacts",
    "BuildMode",
    "BuildRequest",
    "BuildResult",
    "BuildService",
    "CompileResult",
    "__version__",
    "archive_available",
    "build_available",
    "collect_examples",
    "copy_frontend_to_output",
    "find_example_in_repo",
    "find_fastled_repo_upwards",
    "find_fastled_viewer",
    "find_sketch_by_partial_name",
    "find_sketch_directories",
    "get_examples",
    "init_example",
    "init_example_from_repo",
    "is_in_order_match",
    "looks_like_fastled_repo",
    "looks_like_sketch_directory",
    "prepare_sketch_selection",
    "project_available",
    "project_init",
    "read_fastled_json_ref",
    "resolve_prompt_choice",
    "string_diff",
    "version",
    "viewer_available",
    "watch_available",
]
