name: Docker Build Template

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      platform:
        required: true
        type: string
      registry_image:
        required: true
        type: string
      docker_username:
        required: true
        type: string


jobs:
  build:
    runs-on: ${{ inputs.runs_on }}
    strategy:
      fail-fast: false
    steps:
      - name: Prepare
        run: |
          platform=${{ inputs.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry_image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Debug
        run: |
          echo "docker_username=${{ inputs.platform }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.platform }}
          context: https://github.com/zackees/fastled-wasm.git
          file: Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ inputs.registry_image }},push-by-digest=true,name-canonical=true,push=true
          build-args: |
            PLATFORM_TAG=${{ inputs.platform == 'linux/arm64' && '-arm64' || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,compression=zstd
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
            name: digests-${{ env.PLATFORM_PAIR }}
            path: /tmp/digests/*
            if-no-files-found: error
            retention-days: 1