name: Build Webpage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write      # This allows pushing to branches
    
    steps:
    - uses: actions/checkout@v3

    - name: Install UV
      run: pip install uv

    - name: Install dependencies
      run: ./install
      shell: bash
    
    - name: Create index.html
      run: |
        uv run build_site.py
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true    # This creates a new orphan branch each time
