name: Build Webpage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # This allows pushing to branches
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create index.html
      run: |
        mkdir -p site
        echo '<html><head><title>Hello World</title></head><body><h1>Hello World!</h1></body></html>' > site/index.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true    # This creates a new orphan branch each time
