name: Build Compiler for Docker arm64

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.11]
        os: [macos-latest-xlarge]


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 25

    - name: Print platform and cpu arch
      run: |
        echo "platform=$(uname -s)"
        echo "cpu_arch=$(uname -m)"
        echo "cpu_arch=$(uname -m)"

    - name: Install dependencies
      run: |
        bash install
        pip install docker
    - name: Run python build_compiler.py w/ credentials
      run: |
        python build_docker_image.py --docker-pass ${{ secrets.DOCKER_PASSWORD }}
    - name: Now make the executable
      run: uv run build_compiler_exe.py