name: Build and Publish Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*

  build-executables:
    needs: build-and-publish
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install UV
      run: pip install uv

    - name: Install dependencies  
      run: ./install
      shell: bash

    - name: Build executable
      run: uv run build_exe.py

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/fastled
          dist/fastled.exe
        draft: false
        prerelease: false
