name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # This allows pushing to branches
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create and switch to orphan branch
      run: |
        git checkout --orphan temp_pages
        git rm -rf .
        
    - name: Create index.html
      run: |
        echo '<html><head><title>Hello World</title></head><body><h1>Hello World!</h1></body></html>' > index.html
        git add index.html
        
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
    - name: Commit and force push to gh-pages
      run: |
        git commit -m "Deploy to GitHub Pages"
        git branch -D gh-pages || true
        git branch -m gh-pages
        git push -f origin gh-pages
