name: Caller

on:
    push:
      branches:
        - main  # Adjust this to your default branch

jobs:
  credentials:
    runs-on: ubuntu-latest
    outputs:
      docker_username: ${{ steps.credentials.outputs.docker_username }}
      CREDENTIAL2: ${{ steps.credentials.outputs.CREDENTIAL2 }}
    steps:
      - name: Output encoded credentials
        id: credentials
        env:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          CREDENTIAL2: CREDENTIAL2
        run: |
          echo "docker_username=$(echo $docker_username | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          echo "CREDENTIAL2=$(echo $CREDENTIAL2 | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT

  reusable-workflow:
    needs: credentials
    uses: ./.github/workflows/reusable.yml
    secrets:
      env_vars: |
        docker_username=${{ needs.credentials.outputs.docker_username }}
        CREDENTIAL2=${{ needs.credentials.outputs.CREDENTIAL2 }}