name: build wasm compiler

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_USERNAME }}" | docker login -u "${{ secrets.DOCKER_PASSWORD }}" --password-stdin

    - name: Generate timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag ruslanmv/ollama-webui:${TIMESTAMP}
      run: python build_compiler.py --docker-user ${{ secrets.DOCKER_USERNAME }} --docker-pass ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: docker push ruslanmv/ollama-webui:${TIMESTAMP}