name: Create Version Tag

on:
  push:
    branches:
      - main
    paths:
      - 'src/fastled/__init__.py'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Need previous commit to compare

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install UV
      run: pip install uv

    - name: Install dependencies
      run: ./install
      shell: bash

    - name: Get current version
      id: current_version
      run: |
        uv run fastled --version > current_version.txt
        echo "current=$(cat current_version.txt)" >> $GITHUB_OUTPUT

    - name: Get previous version
      id: prev_version
      run: |
        git checkout HEAD~1
        uv run fastled --version > prev_version.txt

    - name: Create Tag if version changed
      if: steps.current_version.outputs.current != steps.prev_version.outputs.previous
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v${{ steps.current_version.outputs.current }}" -m "Release v${{ steps.current_version.outputs.current }}"
        git push origin "v${{ steps.current_version.outputs.current }}"
