name: Ubuntu_Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install UV
      run: pip install uv

    - name: Install
      run: ./install

    - name: Unit tests
      run: ./test

    - name: Build Compiler
      run: uv run build_compiler_exe.py --arch amd64

    - name: Generate timestamp and random hex
      id: generate_id
      run: |
        echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT


    - name: Upload dist folder
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ steps.generate_id.outputs.timestamp }}-${{ github.sha }}
        path: dist/

        